### ISSUE TITLE
Some use cases?

### ISSUE THREAD

**Issue by ahu** [achiku/sample-golang-soap-xml#1]
Sorry for this issue, but I really need examples how to use :(

I have wrote a main.go like below :

> package main
> 
> import (
> 	"fmt"
> 
> 	gosoap "github.com/achiku/sample-golang-soap-xml"
> )
> 
> func main() {
> 	err := gosoap.NewSOAPServer("8888")
> 	fmt.Println("exiting with error", err)
> }

only got this:

> exiting with error &{localhost:8888 0xc000022340 <nil> 0s 0s 0s 0s 0 map[] <nil> <nil> 0 0 {{0 0} 0} <nil> {0 0} map[] map[] <nil> []}

**Comment by ghost** [comment]
`NewSOAPServer(port)` returns a http.Server pointer. You must "start" the server:
```

func main() {
    server := gosoap.NewSOAPServer("8888")
    server.ListenAndServe()
}

```
